controllers/ApiController.php
<?php

namespace app\controllers;

use app\models\Category;
use app\models\News;
use app\modules\appadm\models\NewsCategory;
use Yii;
use yii\data\Pagination;
use yii\db\Query;
use yii\helpers\Json;
use yii\web\Controller;

/**
 * Api Controller
 */
class ApiController extends Controller
{

    /**
     * @return string|\yii\web\Response
     */
    public function actionNews()
    {
        $cat_id = Yii::$app->request->get('cat_id');
        $deep = Yii::$app->request->get('deep', 3);

        $ids = Category::getChildIds($cat_id , $deep);

        $query = new Query();

        $query->select('n.id, n.title, n.text, n.created_at')
            ->innerJoin(['nc' => NewsCategory::tableName()], 'nc.news_id=n.id')
            ->from(['n' => News::tableName()])->indexBy('id')
            ->andWhere(['nc.category_id' =>  $ids,]);

        $countQuery = clone $query;
        $pages = new Pagination([
            'totalCount' => $countQuery->count(),
            'defaultPageSize' => 20, //для примера можно поставить 2
        ]);

        $rows = $query->offset($pages->offset)
            ->limit($pages->limit)
            ->all();

        $json = [
            'pages' => $pages->getLinks(true),
            'news' => $rows
        ];
        return $this->output($json);
    }

    /**
     * @return string|\yii\web\Response
     */
    public function actionCategory()
    {
        $deep = Yii::$app->request->get('deep', 3);
        $categories = Category::getCategories($deep);

        $json = [
            'categories' => $categories
        ];
        return $this->output($json);
    }


    /**
     * @param $json
     * @return string|void
     */
    public function output($json)
    {
        if (Yii::$app->request->get('print')) {
            return $this->render('print', [
                'json' => $json,
            ]);
        }

        return Json::encode($json);
    }

}

views/admpages/default/main.php
<?php

use app\helpers\Url;

/* @var $this yii\web\View */
/* @var $model app\core\admpages\models\Page */

Yii::$app->params['html.canonical'] = Url::to('', true);
$appAsset = \app\assets_b\AppAsset::register($this);

$this->context->layout = '/main';
/*
Yii::$app->params['og']['og:title'] = $this->title;
Yii::$app->params['og']['og:type'] = 'website';
Yii::$app->params['og']['og:url'] = Yii::$app->params['html.canonical'];
Yii::$app->params['og']['og:image'] = Url::to('@web/files/banners/main_banner_' . Yii::$app->language . '.jpg', true);
Yii::$app->params['og']['og:description'] = $model->description;
*/

$categories = \app\models\Category::getCategories();

$print = Yii::$app->request->get('print');


?>

<div class="main-page container">
    <div style="margin: 10px 0px;">
        <a href="<?= Url::current(['print' => 1]) ?>" class="btn btn-primary">print</a>
        <a href="<?= Url::current(['print' => null]) ?>" class="btn btn-primary">json</a>
    </div>

    <div style="border: 1px solid black; margin-bottom: 10px;">
        <ul>
            <?php foreach ($categories as $cat) {?>
                <li>
                    <a href="<?= Url::to(['/api/news', 'cat_id' => $cat['id'], 'deep' => 3, 'print' => $print]) ?>" target="_blank">(<?= $cat['title'] ?>) <?= Url::to(['/api/news', 'cat_id' => $cat['id'], 'deep' => 3, 'print' => $print]) ?></a>
                    <?php if ($cat['children']) {?>
                        <ul>
                            <?php foreach ($cat['children'] as $sub) {?>
                                <li>
                                    <a href="<?= Url::to(['/api/news', 'cat_id' => $sub['id'], 'deep' => 3, 'print' => $print]) ?>" target="_blank">(<?= $sub['title'] ?>) <?= Url::to(['/api/news', 'cat_id' => $sub['id'], 'deep' => 3, 'print' => $print]) ?></a>
                                    <?php if ($sub['children']) {?>
                                        <ul>
                                            <?php foreach ($sub['children'] as $subsub) {?>
                                                <li>
                                                    <a href="<?= Url::to(['/api/news', 'cat_id' => $subsub['id'], 'deep' => 3, 'print' => $print]) ?>" target="_blank">(<?= $subsub['title'] ?>) <?= Url::to(['/api/news', 'cat_id' => $subsub['id'], 'deep' => 3, 'print' => $print]) ?></a>
                                                </li>
                                            <?php }?>
                                        </ul>
                                    <?php }?>
                                </li>
                            <?php }?>
                        </ul>
                    <?php }?>
                </li>
            <?php }?>
        </ul>

    </div>
    <div style="border: 1px solid black; margin-bottom: 10px;">
        <a href="<?= Url::to(['/api/category', 'deep' => 3, 'print' => $print]) ?>" target="_blank"><?= Url::to(['/api/category', 'deep' => 3, 'print' => $print]) ?></a>
    </div>
</div>

views/admpages/default/page.php
<?php

/* @var $this yii\web\View */
/* @var $model app\core\admpages\models\Page */

Yii::$app->params['breadcrumbs'][] = $model->name;
?>
<div class="adm-pages-layout-page">
    <h1><?= $model->title ?></h1>
    <div><?= $model->text ?></div>
</div>